# Generated by Django 5.1.7 on 2025-04-09 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hoteldetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotelname', models.CharField(blank='false', max_length=50, null='false')),
                ('ph_no', models.CharField(blank='false', max_length=10, null='false')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('address', models.CharField(max_length=60)),
            ],
        ),
    ]
